#!/bin/sh
cd "${0%/*}";
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET="14.0" -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DSE_RENDERER="sdl3" -DSE_WINDOWING="sdl3" -DSE_AUDIO_ENGINE="sdl3" -DSE_CLOUDVARS=OFF -DSE_DOWNLOAD=OFF -DSE_USE_LIBRARY_BUILD=OFF && cmake --build build;
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET="14.0" -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DSE_RENDERER="sdl3" -DSE_WINDOWING="sdl3" -DSE_AUDIO_ENGINE="sdl3" -DSE_CLOUDVARS=OFF -DSE_DOWNLOAD=OFF -DSE_USE_LIBRARY_BUILD=ON && cmake --build build;
