FROM pspdev/pspdev:latest AS main_builder
ENV CATALOG_NON_INTERACTIVE=1
WORKDIR /app

COPY . .

RUN psp-cmake -B build/psp -S . -DCMAKE_BUILD_TYPE=Release && make -C build/psp -j 2

FROM scratch AS exporter

COPY --from=main_builder /app/build/psp/scratch-psp.zip /
