FROM debian:trixie AS main_builder
WORKDIR /app

RUN apt-get update && apt-get install -y mingw-w64 wget unzip git pkg-config zip cmake python3 python3-jinja2

COPY . .

# TODO: Fix Cloud Variables
RUN mkdir build && cd build && cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DSE_CLOUDVARS=OFF -DSE_DOWNLOAD=ON -DCMAKE_BUILD_TYPE=Release -DSE_AUDIO_ENGINE=sdl3 -DSE_WINDOWING=sdl3 .. && cmake --build . -j 2

FROM scratch AS exporter
COPY --from=main_builder /app/build/scratch-pc.exe /
