FROM ghcr.io/extremscorner/libogc2:latest AS main_builder
ENV CATALOG_NON_INTERACTIVE=1
WORKDIR /app

COPY . .

RUN /opt/devkitpro/libogc2/gamecube/bin/powerpc-eabi-cmake -B build-gamecube -DCMAKE_BUILD_TYPE=Release && cmake --build build-gamecube -j2

FROM scratch AS exporter
COPY --from=main_builder /app/build-gamecube/scratch-gamecube.zip /
