FROM dkosmari/devkitppc-wiiu-debian:latest AS main_builder
ENV CATALOG_NON_INTERACTIVE=1

COPY . .

RUN sudo -E /opt/devkitpro/portlibs/wiiu/bin/powerpc-eabi-cmake -B build-wiiu -DCMAKE_BUILD_TYPE=Release && sudo -E cmake --build build-wiiu -j2 && sudo -E cmake --build build-wiiu --target package_wiiu

FROM scratch AS exporter
COPY --from=main_builder /project/build-wiiu/scratch-wiiu.zip /
