FROM devkitpro/devkitppc:latest AS main_builder
ENV CATALOG_NON_INTERACTIVE=1
WORKDIR /app

COPY . .

RUN /opt/devkitpro/portlibs/wii/bin/powerpc-eabi-cmake -B build-wii -DCMAKE_BUILD_TYPE=Release && cmake --build build-wii -j2

FROM scratch AS exporter
COPY --from=main_builder /app/build-wii/scratch-wii.zip /
