# If you're editing this, would just like to let you know the insane amount of pain getting this Dockerfile to work was; it literally took me over 12 hrs...

FROM --platform=$BUILDPLATFORM crazymax/osxcross:15.5-alpine AS osxcross

FROM alpine:latest AS main_builder
WORKDIR /app

RUN apk add --no-cache clang lld musl-dev fts cmake make git bash python3 py3-jinja2

COPY --from=osxcross /osxcross /osxcross
ENV PATH="/osxcross/bin:$PATH"
ENV LD_LIBRARY_PATH="/osxcross/lib"
ENV MACOSX_DEPLOYMENT_TARGET="14.0"

COPY . .

ARG ARCH=x86_64

# TODO: Cloud Variables
RUN mkdir build && cd build && \
	${ARCH}-apple-darwin24.5-cmake \
	-DCMAKE_OSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET \
	-DSE_CLOUDVARS=OFF \
	-DSE_DOWNLOAD=OFF \
	-DSE_AUDIO_ENGINE=sdl2 \
	-DSE_WINDOWING=sdl2 \
	-DCMAKE_BUILD_TYPE=Release \
	.. && \
	cmake --build . -j 2

FROM scratch AS exporter
COPY --from=main_builder /app/build/scratch-pc /
