set(SE_DEFAULT_OUTPUT_NAME "scratch-ds")

set(SE_RENDERER_VALID_OPTIONS "gl2d")
set(SE_AUDIO_ENGINE_VALID_OPTIONS "nds")
set(SE_DEPS_VALID_OPTIONS "fallback" "system")

set(SE_CACHING_DEFAULT OFF)

set(SE_ALLOW_CMAKERC OFF)
set(SE_ALLOW_CLOUDVARS OFF)
set(SE_ALLOW_DOWNLOAD OFF)

set(SE_PLATFORM_DEFINITIONS "__NDS__" "ARM9")
set(SE_PLATFORM "nds")

set(SE_HAS_THREADS OFF)

set(SE_HAS_TOUCH TRUE)
set(SE_HAS_MOUSE FALSE)
set(SE_HAS_KEYBOARD FALSE)
set(SE_HAS_CONTROLLER TRUE)

macro(package_platform)
	nds_create_rom(scratch-everywhere
		NAME "${SE_APP_NAME}"
		SUBTITLE "${SE_APP_DESCRIPTION}"
		AUTHOR "${SE_APP_AUTHOR}"
		ICON "${CMAKE_CURRENT_SOURCE_DIR}/gfx/nds/icon.bmp"
		NITROFS "${CMAKE_CURRENT_SOURCE_DIR}/romfs"
	)
endmacro()
