# Fetches and includes Catalog automatically.
#
# This file is intended to be vendored.
#
# Settings (as a CMake variable, or matching env var - variable wins; each accepts a CATALOG_BOOTSTRAP_, CL_BOOTSTRAP_, or CLB_ prefix):
#   *_VERSION   release tag to fetch. Default: nightly
#   *_UPDATE    ALWAYS | NEVER | <seconds since last fetch before re-checking>. Default: 86400 (1 day)
#   *_MINIFIED  ON/OFF - fetch catalog.min.cmake vs the readable catalog.cmake. Default: ON
#   *_URL       full override URL, e.g. for an internal mirror - skips the release-tag URL entirely
#   *_LOCAL     force a project-local cache dir instead of the shared machine-wide one (same effect
#               as Catalog's own CATALOG_LOCAL_CACHE, which is also respected here)

if(DEFINED __CATALOG_BOOTSTRAPPED)
  return()
endif()
set(__CATALOG_BOOTSTRAPPED TRUE)

function(_clb_setting SUFFIX DEFAULT OUT_VAR)
  foreach(_CLB_PREFIX CATALOG_BOOTSTRAP_ CL_BOOTSTRAP_ CLB_)
    if(DEFINED ${_CLB_PREFIX}${SUFFIX})
      set(${OUT_VAR} "${${_CLB_PREFIX}${SUFFIX}}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(_CLB_PREFIX CATALOG_BOOTSTRAP_ CL_BOOTSTRAP_ CLB_)
    if(DEFINED ENV{${_CLB_PREFIX}${SUFFIX}} AND NOT "$ENV{${_CLB_PREFIX}${SUFFIX}}" STREQUAL "")
      set(${OUT_VAR} "$ENV{${_CLB_PREFIX}${SUFFIX}}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${OUT_VAR} "${DEFAULT}" PARENT_SCOPE)
endfunction()

_clb_setting(VERSION "nightly" _CLB_VERSION)
_clb_setting(UPDATE "86400" _CLB_UPDATE)
_clb_setting(MINIFIED "ON" _CLB_MINIFIED)
_clb_setting(URL "" _CLB_URL_OVERRIDE)
_clb_setting(LOCAL "" _CLB_LOCAL)

function(_clb_catalog_setting SUFFIX DEFAULT OUT_VAR)
  foreach(_CLB_PREFIX CATALOG_ CL_)
    if(DEFINED ${_CLB_PREFIX}${SUFFIX})
      set(${OUT_VAR} "${${_CLB_PREFIX}${SUFFIX}}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  foreach(_CLB_PREFIX CATALOG_ CL_)
    if(DEFINED ENV{${_CLB_PREFIX}${SUFFIX}} AND NOT "$ENV{${_CLB_PREFIX}${SUFFIX}}" STREQUAL "")
      set(${OUT_VAR} "$ENV{${_CLB_PREFIX}${SUFFIX}}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${OUT_VAR} "${DEFAULT}" PARENT_SCOPE)
endfunction()

_clb_catalog_setting(CACHE_DIR "" _CLB_CACHE_DIR_OVERRIDE)
_clb_catalog_setting(LOCAL_CACHE "" _CLB_LOCAL_CACHE)
if(NOT "${_CLB_CACHE_DIR_OVERRIDE}" STREQUAL "")
  set(_CLB_CACHE_DIR "${_CLB_CACHE_DIR_OVERRIDE}")
elseif(CMAKE_CROSSCOMPILING OR NOT "${_CLB_LOCAL_CACHE}" STREQUAL "" OR NOT "${_CLB_LOCAL}" STREQUAL "")
  set(_CLB_CACHE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/.cache/catalog")
elseif(WIN32)
  set(_CLB_CACHE_DIR "$ENV{LOCALAPPDATA}/catalog")
else()
  set(_CLB_CACHE_DIR "$ENV{HOME}/.cache/catalog")
endif()
set(_CLB_CACHE_DIR "${_CLB_CACHE_DIR}/bootstrap")
file(MAKE_DIRECTORY "${_CLB_CACHE_DIR}")

if(_CLB_MINIFIED)
  set(_CLB_ASSET "catalog.min.cmake")
else()
  set(_CLB_ASSET "catalog.cmake")
endif()

if(NOT "${_CLB_URL_OVERRIDE}" STREQUAL "")
  set(_CLB_URL "${_CLB_URL_OVERRIDE}")
else()
  set(_CLB_URL "https://github.com/catalog-cmake/catalog/releases/download/${_CLB_VERSION}/${_CLB_ASSET}")
endif()

set(_CLB_CACHED_FILE "${_CLB_CACHE_DIR}/${_CLB_VERSION}-${_CLB_ASSET}")
set(_CLB_STAMP_FILE "${_CLB_CACHED_FILE}.stamp")

set(_CLB_NEED_DOWNLOAD TRUE)
if(EXISTS "${_CLB_CACHED_FILE}")
  if(_CLB_UPDATE STREQUAL "NEVER")
    set(_CLB_NEED_DOWNLOAD FALSE)
  elseif(NOT _CLB_UPDATE STREQUAL "ALWAYS" AND EXISTS "${_CLB_STAMP_FILE}")
    file(TIMESTAMP "${_CLB_STAMP_FILE}" _CLB_STAMP_TIME "%s" UTC)
    string(TIMESTAMP _CLB_NOW "%s" UTC)
    math(EXPR _CLB_AGE "${_CLB_NOW} - ${_CLB_STAMP_TIME}")
    if(_CLB_AGE LESS "${_CLB_UPDATE}")
      set(_CLB_NEED_DOWNLOAD FALSE)
    endif()
  endif()
endif()

if(_CLB_NEED_DOWNLOAD)
  message(STATUS "[Catalog Bootstrap] Fetching Catalog (${_CLB_VERSION})...")
  file(DOWNLOAD "${_CLB_URL}" "${_CLB_CACHED_FILE}.tmp" STATUS _CLB_DL_STATUS TIMEOUT 30)
  list(GET _CLB_DL_STATUS 0 _CLB_DL_CODE)
  if(_CLB_DL_CODE EQUAL 0)
    file(RENAME "${_CLB_CACHED_FILE}.tmp" "${_CLB_CACHED_FILE}")
    file(TOUCH "${_CLB_STAMP_FILE}")
  else()
    file(REMOVE "${_CLB_CACHED_FILE}.tmp")
    if(EXISTS "${_CLB_CACHED_FILE}")
      list(GET _CLB_DL_STATUS 1 _CLB_DL_ERR)
      message(WARNING "[Catalog Bootstrap] Update check failed (${_CLB_DL_ERR}), using cached copy from ${_CLB_STAMP_FILE}")
    else()
      list(GET _CLB_DL_STATUS 1 _CLB_DL_ERR)
      message(FATAL_ERROR "[Catalog Bootstrap] Failed to download Catalog from ${_CLB_URL}: ${_CLB_DL_ERR}")
    endif()
  endif()
endif()

include("${_CLB_CACHED_FILE}")
